# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jv5om2l6iGrtkdRIj8A2ymsVtXr1E5nq
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("tips.csv")

data.head(10)

data.info()

data.describe()

plt.figure(figsize=(3,3))
plt.bar(data['day'], data['tip'],label='$',color='#b3a6c4', edgecolor='black')
plt.title('Amount of tips vs Days', fontsize= 12, fontname='cursive', fontweight='bold',color='#283747')
plt.xlabel('Days', fontsize= 10, fontname='cursive', fontweight='bold',color='#283747')
plt.ylabel('Tip', fontsize= 10, fontname='cursive', fontweight='bold',color='#283747')
plt.legend()
plt.show()

plt.figure(figsize=(4,3))
plt.pie(data['sex'].value_counts(), labels=data['sex'].value_counts().index, autopct='%.2f%%', colors=['rosybrown','gray'])
plt.title('Male to Female percentage of customers', fontsize= 10, fontname='cursive', fontweight='bold', color='#283747')
plt.show()

plt.figure(figsize=(3,3))
plt.scatter(data['size'], data.tip, label='Amt',c=data['tip'], cmap='viridis', s=100, alpha=0.5)
plt.title('Size of the group vs Tip amount',fontsize= 16, fontname='cursive', fontweight='bold', color='#283747')
plt.xlabel('No.of customers in the group', fontsize= 10, fontname= 'cursive', color='#283747')
plt.ylabel('Tip amount', fontsize= 10, fontname= 'cursive', color='#283747')
plt.colorbar()
plt.show()

plt.figure(figsize=(3,3))
plt.bar(data['time'], data.total_bill, label='Total Bill', color=['#34495E'], hatch='/')
plt.title('Bill made during Lunch & Dinner times', fontsize= 13, fontname='cursive', fontweight='bold',color= '#264348')
plt.ylabel('Total bill in dollars ($)', fontsize= 10, fontname= 'cursive', color='#283747')
plt.xlabel('Time of the day', fontsize= 10, fontname= 'cursive', color='#283747')
plt.legend()
plt.show()

plt.figure(figsize=(3,3))
plt.scatter(data['tip'], data['total_bill'], s=100, alpha=0.5, marker='')
plt.title('Total bill and the tip amount',fontsize= 16, fontname='cursive', fontweight='bold', color='#665d1e')
plt.xlabel('Tip amount', fontsize= 10, fontname= 'cursive', color='#665d1e')
plt.ylabel('Total bill', fontsize= 10, fontname= 'cursive', color='#665d1e')
#Sort data by 'tip' for line plot
sorted_data = data.sort_values('tip')
# Add line plot
plt.plot(sorted_data['tip'], sorted_data['total_bill'],color='#707B7C')
plt.show()

plt.figure(figsize=(5, 5), facecolor='#34495E')
line,=plt.plot((data['total_bill'].describe()), marker='^',linewidth=2, markersize=2,markerfacecolor='#34495E', markeredgewidth=2, markeredgecolor='#34495E', label='total bill')
plt.ylabel('Values in dollars ($)', fontsize= 10, fontname= 'cursive', color='#CCD1D1')
plt.xlabel('Statistics of the total bill.'  , fontsize= 10, fontname= 'cursive', color='#CCD1D1')
for x, y in zip(line.get_xdata(), line.get_ydata()):
    #annotate to add annotation of each point and f{y:.2f} formats the value to nearest integer
    plt.annotate(f'{y:.0f}', (x, y), textcoords="offset points", xytext=(0,3), ha='left', color='#34495E')
    #specifies the values should be placed ten points above the line and text alignment should be left
plt.legend()
plt.show()

plt.figure(figsize=(3,3))
plt.hist(data['total_bill'], bins=10, color='#34495E', edgecolor='black')
plt.title('Distribution of the total bill', fontsize= 12, fontname='cursive', fontweight='bold',color='#283747')
plt.xlabel('Total bill in dollars ($)', fontsize= 10, fontname='cursive', fontweight='bold',color='#283747')
plt.ylabel('Frequency of the bill', fontsize= 10, fontname='cursive', fontweight='bold',color='#283747')
plt.show()

